# Generated by Django 2.2.2 on 2019-06-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSummaryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('units', models.CharField(max_length=25)),
                ('icon', models.CharField(max_length=150)),
                ('baseline_max', models.FloatField(default=None)),
                ('actual', models.FloatField(default=None)),
                ('model', models.FloatField(default=None)),
                ('difference', models.FloatField(default=None)),
                ('bar_total_width', models.SmallIntegerField(default=160)),
                ('bar_left_width', models.SmallIntegerField(default=None)),
                ('bar_mid_width', models.SmallIntegerField(default=None)),
                ('bar_right_width', models.SmallIntegerField(default=None)),
                ('exceeds_model', models.BooleanField()),
            ],
        ),
    ]
