# Generated by Django 2.2.2 on 2019-06-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardsummaryitem',
            name='group',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dashboardsummaryitem',
            name='varname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboardsummaryitem',
            name='icon',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='dashboardsummaryitem',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dashboardsummaryitem',
            name='units',
            field=models.CharField(default='', max_length=25),
        ),
    ]
