# Generated by Django 2.2.2 on 2019-06-18 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_auto_20190618_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeriesEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('data', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSeriesHighlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('varname', models.CharField(default='', max_length=50)),
                ('has_secondary_axis', models.BooleanField(default=False)),
                ('units', models.CharField(default='', max_length=25)),
                ('xaxis_label', models.CharField(default='', max_length=100)),
                ('yaxis_label', models.CharField(default='', max_length=100)),
                ('units_secondary', models.CharField(default='', max_length=25)),
                ('yaxis_label_secondary', models.CharField(default='', max_length=100)),
                ('display_start', models.DateTimeField()),
                ('display_end', models.DurationField(default=datetime.timedelta(days=1))),
                ('entries', models.ManyToManyField(related_name='entries', to='ui.TimeSeriesEntry')),
            ],
        ),
    ]
