# Generated by Django 2.2.2 on 2019-06-18 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_auto_20190618_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeserieshighlight',
            name='display_end',
        ),
        migrations.RemoveField(
            model_name='timeserieshighlight',
            name='display_start',
        ),
    ]
