# Generated by Django 3.0.3 on 2020-03-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BokehApps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardDataRTO',
        ),
        migrations.DeleteModel(
            name='ForecastsMarketData',
        ),
        migrations.DeleteModel(
            name='ForecastsSolarData',
        ),
    ]
