# Generated by Django 3.0.3 on 2020-03-15 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BokehApps', '0003_dashboarddatarto_forecastsmarketdata_forecastssolardata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardDataRTO',
        ),
        migrations.DeleteModel(
            name='ForecastsMarketData',
        ),
        migrations.DeleteModel(
            name='ForecastsSolarData',
        ),
    ]
